name: CI

on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]
  workflow_dispatch:

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install Packages
        run: HUSKY=0 pnpm install
      - name: Lint Files
        run: pnpm run lint

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install Packages
        run: HUSKY=0 pnpm install
      - name: Tests
        run: pnpm run test
