name: CI

on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install Packages
        run: HUSKY=0 pnpm install

  ci:
    name: ${{ matrix.task }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: Lint
            command: pnpm run lint
          - task: Build
            command: pnpm run build
          - task: Test
            command: pnpm run test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: HUSKY=0 pnpm install
      - run: ${{ matrix.command }}
