name: Publish Stable

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-node-pnpm
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Lint Files
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Tests
        run: pnpm run test

      - name: Publish
        run: pnpm publish --access public --no-git-checks
