name: Publish Stable

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Dependencies
        run: HUSKY=0 pnpm install --frozen-lockfile

      - name: Lint Files
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Tests
        run: pnpm run test

      - name: Publish
        run: pnpm publish --access public --no-git-checks
